# Generated by Django 4.1.7 on 2023-03-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='funcionarios',
        ),
    ]
