# Generated by Django 4.1.7 on 2023-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0003_alter_dvd_caminho_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='caminho_imagem',
            field=models.CharField(default='../templates/static/dvds/img/default.png', max_length=500),
        ),
    ]
