# Generated by Django 4.1.7 on 2023-03-05 00:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('dvds', '0004_alter_dvd_caminho_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='dvd',
            name='aluguel_dvd_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvd',
            name='valor_aluguel',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='lista_espera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientes', models.ManyToManyField(to='dvds.clientes')),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.dvd')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='dvds',
            field=models.ManyToManyField(to='dvds.dvd'),
        ),
    ]
