# Generated by Django 4.1.7 on 2023-03-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0005_clientes_dvd_aluguel_dvd_pago_dvd_valor_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_espera',
            name='nome',
            field=models.CharField(default='dvd.titulo', max_length=50),
        ),
    ]
