# Generated by Django 4.1.7 on 2023-03-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0006_lista_espera_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_espera',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='lista_espera',
            name='dvd',
        ),
        migrations.AddField(
            model_name='dvd',
            name='lista_espera',
            field=models.CharField(default=[], max_length=255),
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.DeleteModel(
            name='lista_espera',
        ),
    ]
