# Generated by Django 4.1.7 on 2023-03-05 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvds', '0007_remove_lista_espera_clientes_remove_lista_espera_dvd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.dvd')),
            ],
        ),
    ]
