# Generated by Django 4.1.7 on 2023-03-09 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0009_remove_dvd_aluguel_dvd_pago_remove_dvd_valor_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 29, 41, 366)),
        ),
    ]
