# Generated by Django 4.1.7 on 2023-03-09 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0012_remove_dvd_lista_espera_alter_aluguel_data_aluguel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 17, 31, 59, 88490)),
        ),
    ]
