# Generated by Django 4.1.7 on 2023-03-09 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0013_alter_aluguel_data_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='lista_espera_dvd',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 18, 57, 22, 952583)),
        ),
        migrations.DeleteModel(
            name='lista_espera',
        ),
    ]
