# Generated by Django 4.1.7 on 2023-03-09 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvds', '0014_dvd_lista_espera_dvd_alter_aluguel_data_aluguel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 19, 4, 52, 874528)),
        ),
    ]
