# Generated by Django 4.1.7 on 2023-03-11 20:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvds', '0015_alter_aluguel_data_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 17, 51, 11, 58932)),
        ),
        migrations.CreateModel(
            name='lista_espera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvds.dvd')),
            ],
        ),
    ]
